server.port=8090

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=informe;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver