CREATE TABLE IF NOT EXISTS Atendidos_Servicio (
    ID_USU VARCHAR(50),
    FEC_ING DATE,
    TIP_CAR VARCHAR(100),
    SEX_USU INT,
    EDAD_USU INT
);

CREATE TABLE IF NOT EXISTS Beneficiarios_Asistencia_clean (
    ID_USU VARCHAR(50),
    EDAD_BENEF INT,
    SEX_USU INT,
    DEP_RES VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Beneficiarios_Atendidos_clean (
    ID_USU VARCHAR(50),
    NOM_SER VARCHAR(200),
    SEX_USU INT,
    EDAD_USU INT,
    DEP_CA VARCHAR(100)
);
